[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
dependencies = [
    "osgeo>=3.3.3",
    "geopandas>=0.8.1",
    "shapely>=1.8.0",
    "requests>=2.24.0",
    "pandas>=1.3.4",
    "joblib>=0.17.0",
]
build-backend = "setuptools.build_meta"